### ISSUE TITLE
How to install php Phalcon for EasyApache 4

### ISSUE THREAD

**Issue by muddassirnazir** [thecpaneladmin/EA-PhalconPHP#10]
The directory /var/cpanel/easy/apache/custom_opt_mods/ doesn't exists in WHM 58.0.(build 25).
<br />So, which folder contains the custom modules for easyapache 4 ?

**Comment by vanessavasile** [comment]
This specific plugin is for EA3. EA4 does not use opt mods, it uses RPMs.
