### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by gabuuzz** [thecpaneladmin/EA-PhalconPHP#2]
Hello,

The easyapache integration doesn't seem to work with PHP 5.6

Getting this error:
All Phalcon classes doesn't exist. (not found)

Warning: PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so: cannot open shared object file: No such file or directory in Unknown on line 0

CentOS 6.7 with WHM 11.50.2 (build 0) and easyapache v3.32.2

It work perfectly for now with PHP 5.5

Thank you in advance

**Comment by eede** [comment]
Hello @gabuuzz 

I had the same issue and solution for it seems to upgrading  PostgreSQL.

You can update it by using below command:

```
/usr/local/cpanel/scripts/installpostgres
```

**Comment by gabuuzz** [comment]
Thank you for the reply @eede 

I'm not using PostgreSQL currently.

 I think I managed to fix it by recompiling in php 5.6 without phlacon and a second time with phalcon.
