### ISSUE TITLE
EA build Error

### ISSUE THREAD

**Issue by labane** [thecpaneladmin/EA-PhalconPHP#3]
Hi, 
Please assist me with the following error I get when I build my EA3 with Phalcon enabled.

    -- Begin step 'make' --
/bin/sh /home/cpeasyapache/src/cphalcon-master/ext/libtool --mode=compile cc  -I. -I/home/cpeasyapache/src/cphalcon-master/ext -DPHP_ATOM_INC -I/home/cpeasyapache/src/cphalcon-master/ext/include -I/home/cpeasyapache/src/cphalcon-master/ext/main -I/home/cpeasyapache/src/cphalcon-master/ext -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /home/cpeasyapache/src/cphalcon-master/ext/phalcon.c -o phalcon.lo 
mkdir .libs
cc -I. -I/home/cpeasyapache/src/cphalcon-master/ext -DPHP_ATOM_INC -I/home/cpeasyapache/src/cphalcon-master/ext/include -I/home/cpeasyapache/src/cphalcon-master/ext/main -I/home/cpeasyapache/src/cphalcon-master/ext -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /home/cpeasyapache/src/cphalcon-master/ext/phalcon.c  -fPIC -DPIC -o .libs/phalcon.o
In file included from /usr/local/include/php/ext/spl/spl_iterators.h:27,
                 from /home/cpeasyapache/src/cphalcon-master/ext/kernel/main.h:25,
                 from /home/cpeasyapache/src/cphalcon-master/ext/phalcon.c:24:
/usr/local/include/php/ext/pcre/php_pcre.h:29:18: error: pcre.h: No such file or directory
In file included from /usr/local/include/php/ext/spl/spl_iterators.h:27,
                 from /home/cpeasyapache/src/cphalcon-master/ext/kernel/main.h:25,
                 from /home/cpeasyapache/src/cphalcon-master/ext/phalcon.c:24:
/usr/local/include/php/ext/pcre/php_pcre.h:37: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
/usr/local/include/php/ext/pcre/php_pcre.h:38: error: expected '=', ',', ';', 'asm' or '__attribute__' before '*' token
/usr/local/include/php/ext/pcre/php_pcre.h:44: error: expected specifier-qualifier-list before 'pcre'
make: *** [phalcon.lo] Error 1
!! 'make' failed with exit code '512' !!

**Comment by vanessavasile** [comment]
Make sure pcre-devel is installed. The update I just pushed will not install pcre-devel automatically.
