### ISSUE TITLE
Phalcon extension not showing on easy apache

### ISSUE THREAD

**Issue by afbora** [thecpaneladmin/EA-PhalconPHP#5]
````
cd /usr/src
wget https://github.com/thecpaneladmin/EA-PhalconPHP/archive/master.zip
unzip -d /var/cpanel/easy/apache/custom_opt_mods/ master.zip
/scripts/easyapache
````

I tried with this commands but Phalcon extension not listed on EasyApache ssh or interface.

What can i do?

**Comment by vanessavasile** [comment]
Make sure the plugin folder is directly in /var/cpanel/easy/apache/custom_opt_mods/. Usually when the plugin does not show up in the interface it's because the folder is not in the right location.

**Comment by afbora** [comment]
@vanessavasile path is correct.

**Comment by vanessavasile** [comment]
I just followed the exact steps you pasted, and I see 'Phalcon' listed in the PHP options when running EA. So it does appear to be working properly.
