### ISSUE TITLE
Custom module not showing

### ISSUE THREAD

**Issue by zfarhad** [thecpaneladmin/EA-PhalconPHP#7]
Hi,

I try to install phalcon from here, But Phalcon not showing in easy apache modules selection list.
I try to instal another custom module and that showed on selection list, So this custom module has problem with EA or some dependencies not documented.

Finally I have installed phalcon from source code and it worked properly now.

Thanks

**Comment by vanessavasile** [comment]
We've received reports of this, and each time it was due to the module not being located in the correct location. Please paste the exact commands you used when you tried to install the module.

**Comment by zfarhad** [comment]
I have used this documentation:
cd /usr/src
wget https://github.com/thecpaneladmin/EA-PhalconPHP/archive/master.zip
unzip -d /var/cpanel/easy/apache/custom_opt_mods/ master.zip
/scripts/easyapache

Files is located in "/var/cpanel/easy/apache/custom_opt_mods/EA-PhalconPHP-master" after extracting, So I move all files to "/var/cpanel/easy/apache/custom_opt_mods".
Finally PhalconPHP.pm is located in "/var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/PHP5"

All paths is correct, I think.

**Comment by vanessavasile** [comment]
Your structure should look like this:

/var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/PHP5/PhalconPHP.pm
