### ISSUE TITLE
Custom module appears only on console, not gui, doesn't build

### ISSUE THREAD

**Issue by williamsaul** [thecpaneladmin/EA-PhalconPHP#9]
Pathing seems correct according to what I've seen in other posts.

[root@server PHP5]# ls -l
-rw-r--r--. 1 root root 5779 Jun 29 16:34 PhalconPHP.pm
[root@server PHP5]# pwd
/var/cpanel/easy/apache/custom_opt_mods/Cpanel/Easy/PHP5

Running easyapache from GUI shows nothing, running from console actually shows a box to put a check in during exhaustive options, but no name next to it, and Phalcon doesn't get added when the box is checked.

Not sure what else to check. I assume it's something obvious I'm missing. Ideas are appreciated.

**Comment by ispweb** [comment]
We have exact the same problems on an new cpanel server, trying to install the custom module. No GUI and an empty checkbox when running from console. Is there an fix on the way for this (i think) a bug.

**Comment by vanessavasile** [comment]
You may need to do a manual install for now. We are looking into it, but it seems to be related to some recent changes in cPanel in regards to the Perl path.

**Comment by wickyboy** [comment]
I'm also having an issue which looks just like this one.

I have found:

- When installed with php 5.5.x using the blank option from console then phalcon installs.

- When installed with php 5.6.x using the blank option from console then phalcon does not install.

When I say from console I mean I have logged in as root into my server and executed:

`root@s [~]# /scripts/easyapache `

**Comment by baychae** [comment]
bump

**Comment by vanessavasile** [comment]
something changed in EA3 to not allow this to work as it previously did. however, EA3 is now deprecated and can't even be used on newly-installed systems running cPanel 58 or higher. Therefore, we're not supporting this module anymore.

**Comment by wickyboy** [comment]
...and in EA4?

**Comment by vanessavasile** [comment]
see: https://github.com/CpanelInc/scl-phalcon

**Comment by wickyboy** [comment]
Awesome stuff.

Funnily enough I had a CPanel instance up last week and used this to great success.

Thanks so much!!!!
